In [7]:
# Import libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# -----------------------------
# Load IRIS dataset
# -----------------------------
iris = pd.read_csv("/content/iris (1).csv")

# Display first few rows
print("IRIS Dataset Preview:")
print(iris.head())

# Separate features and target
X = iris.iloc[:, :-1]   # all columns except last
y = iris.iloc[:, -1]    # last column (target)

# Encode target if it is categorical
if y.dtype == 'object':
    le = LabelEncoder()
    y = le.fit_transform(y)

# Split into training (80%) and testing (20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create Decision Tree model
model_iris = DecisionTreeClassifier(random_state=42)

# Train model
model_iris.fit(X_train, y_train)

# Predictions
y_pred = model_iris.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("\nIRIS Accuracy:", accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("\nIRIS Confusion Matrix:\n", cm)

IRIS Dataset Preview:
   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

IRIS Accuracy: 1.0

IRIS Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [8]:
# -----------------------------
# Load Drug dataset
# -----------------------------
drug = pd.read_csv("drug.csv")

print("\nDrug Dataset Preview:")
print(drug.head())

# Separate features and target
X = drug.iloc[:, :-1]
y = drug.iloc[:, -1]

# Encode categorical columns in features
X_encoded = X.copy()

for col in X_encoded.columns:
    if X_encoded[col].dtype == 'object':
        le = LabelEncoder()
        X_encoded[col] = le.fit_transform(X_encoded[col])

# Encode target column
if y.dtype == 'object':
    le_target = LabelEncoder()
    y = le_target.fit_transform(y)

# Split into training (80%) and testing (20%)
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42
)

# Create Decision Tree model
model_drug = DecisionTreeClassifier(random_state=42)

# Train model
model_drug.fit(X_train, y_train)

# Predictions
y_pred = model_drug.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("\nDrug Dataset Accuracy:", accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("\nDrug Dataset Confusion Matrix:\n", cm)


Drug Dataset Preview:
   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

Drug Dataset Accuracy: 1.0

Drug Dataset Confusion Matrix:
 [[ 6  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 15]]


In [9]:
# Import required libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

# -----------------------------------
# Load the dataset
# -----------------------------------
data = pd.read_csv("petrol_consumption.csv")

print("Dataset Preview:")
print(data.head())

# -----------------------------------
# Separate features and target
# -----------------------------------
X = data.iloc[:, :-1]   # Independent variables
y = data.iloc[:, -1]    # Dependent variable (Petrol Consumption)

# -----------------------------------
# Split data into 80% training and 20% testing
# -----------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# -----------------------------------
# Create Decision Tree Regressor model
# -----------------------------------
model = DecisionTreeRegressor(random_state=42)

# Train the model
model.fit(X_train, y_train)

# -----------------------------------
# Make predictions
# -----------------------------------
y_pred = model.predict(X_test)

# -----------------------------------
# Evaluation Metrics
# -----------------------------------
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

# -----------------------------------
# Display results
# -----------------------------------
print("\nModel Evaluation Metrics:")
print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)

Dataset Preview:
   Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410  

Model Evaluation Metrics:
Mean Absolute Error (MAE): 94.3
Mean Squared Error (MSE): 17347.7
Root Mean Squared Error (RMSE): 131.7106677532234
